-- =============================================================================
-- 0000_initial.sql
--
-- Initial substrate migration. Creates extensions, enums, and the core L0/L1
-- and L2 ontology tables required for tenancy + first writes. Subsequent
-- migrations (generated by drizzle-kit) layer the remaining tables on top.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Extensions
-- ---------------------------------------------------------------------------
create extension if not exists "uuid-ossp";
create extension if not exists "pgcrypto";
create extension if not exists "citext";
create extension if not exists "pg_trgm";
create extension if not exists "ltree";
create extension if not exists "vector";
-- create extension if not exists "postgis";       -- enable in v2 (geotime)
-- create extension if not exists "btree_gist";    -- enable for tstzrange exclusions

-- ---------------------------------------------------------------------------
-- Enums (subset; remaining created by drizzle-kit in 0001+)
-- ---------------------------------------------------------------------------
do $$ begin
  create type scope_kind as enum ('platform','agency','workspace','public','user','team');
exception when duplicate_object then null; end $$;

do $$ begin
  create type membership_status as enum ('invited','active','suspended','revoked');
exception when duplicate_object then null; end $$;

do $$ begin
  create type sensitivity as enum ('public','internal','confidential','restricted');
exception when duplicate_object then null; end $$;

do $$ begin
  create type link_kind as enum ('1:1','1:N','N:M');
exception when duplicate_object then null; end $$;

do $$ begin
  create type actor_kind as enum ('user','agent','system');
exception when duplicate_object then null; end $$;

-- ---------------------------------------------------------------------------
-- Tenancy
-- ---------------------------------------------------------------------------
create table if not exists public.platforms (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null,
  settings jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);
create unique index if not exists platforms_slug_uq on public.platforms(slug);

create table if not exists public.agencies (
  id uuid primary key default gen_random_uuid(),
  platform_id uuid not null references public.platforms(id) on delete restrict,
  name text not null,
  slug text not null,
  brand_identity_id uuid,
  billing_config_id uuid,
  settings jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);
create index if not exists agencies_platform_idx on public.agencies(platform_id);
create unique index if not exists agencies_platform_slug_uq on public.agencies(platform_id, slug);

create table if not exists public.workspaces (
  id uuid primary key default gen_random_uuid(),
  platform_id uuid not null references public.platforms(id) on delete restrict,
  agency_id uuid references public.agencies(id) on delete set null,
  name text not null,
  slug text not null,
  vertical_pack_id uuid,
  brand_identity_id uuid,
  settings jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);
create index if not exists workspaces_platform_idx on public.workspaces(platform_id);
create index if not exists workspaces_agency_idx on public.workspaces(agency_id);
create unique index if not exists workspaces_platform_slug_uq on public.workspaces(platform_id, slug);

create table if not exists public.users (
  id uuid primary key,
  email citext not null,
  display_name text,
  avatar_url text,
  locale text not null default 'en-US',
  timezone text not null default 'UTC',
  settings jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);
create unique index if not exists users_email_uq on public.users(email);

create table if not exists public.memberships (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  scope scope_kind not null,
  scope_id uuid not null,
  role text not null,
  scopes jsonb not null default '[]'::jsonb,
  status membership_status not null default 'invited',
  invited_at timestamptz not null default now(),
  accepted_at timestamptz,
  suspended_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists memberships_scope_idx on public.memberships(scope, scope_id);
create index if not exists memberships_user_idx on public.memberships(user_id);
create unique index if not exists memberships_user_scope_uq on public.memberships(user_id, scope, scope_id);

-- ---------------------------------------------------------------------------
-- L0
-- ---------------------------------------------------------------------------
create table if not exists public.l0_artifacts (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id) on delete restrict,
  source_kind text not null,
  source_uri text,
  source_connector_instance_id uuid,
  mime_type text not null,
  sha256 text not null,
  byte_size bigint not null,
  storage_bucket text not null,
  storage_key text not null,
  ingested_by_user_id uuid,
  ingested_by_agent text,
  ingested_at timestamptz not null default now(),
  captured_at timestamptz,
  immutable boolean not null default true,
  retention_until timestamptz,
  sensitivity sensitivity not null default 'internal',
  pii_tags text[] not null default '{}',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);
create index if not exists l0_artifacts_workspace_idx on public.l0_artifacts(workspace_id);
create index if not exists l0_artifacts_sha256_idx on public.l0_artifacts(workspace_id, sha256);
create index if not exists l0_artifacts_source_kind_idx on public.l0_artifacts(workspace_id, source_kind);
create index if not exists l0_artifacts_ingested_at_idx on public.l0_artifacts(workspace_id, ingested_at);

-- Block UPDATE/DELETE on immutable L0 artifacts via trigger (immutability invariant).
create or replace function public.l0_block_mutations() returns trigger as $$
begin
  if tg_op = 'DELETE' and old.immutable then
    raise exception 'l0_artifacts are immutable: deletion of % blocked', old.id;
  end if;
  if tg_op = 'UPDATE' and old.immutable then
    if (new.sha256 is distinct from old.sha256)
       or (new.storage_key is distinct from old.storage_key)
       or (new.byte_size is distinct from old.byte_size)
       or (new.mime_type is distinct from old.mime_type) then
      raise exception 'l0_artifacts are immutable: content-addressable fields of % cannot change', old.id;
    end if;
  end if;
  return new;
end;
$$ language plpgsql;

drop trigger if exists l0_artifacts_immutability on public.l0_artifacts;
create trigger l0_artifacts_immutability
  before update or delete on public.l0_artifacts
  for each row execute function public.l0_block_mutations();

create table if not exists public.l0_chunks (
  id uuid primary key default gen_random_uuid(),
  l0_id uuid not null references public.l0_artifacts(id) on delete cascade,
  workspace_id uuid not null references public.workspaces(id) on delete restrict,
  ordinal int not null,
  start_offset int not null,
  end_offset int not null,
  text text not null,
  token_count int,
  embedding vector(1536),
  created_at timestamptz not null default now()
);
create index if not exists l0_chunks_l0_idx on public.l0_chunks(l0_id, ordinal);
create index if not exists l0_chunks_workspace_idx on public.l0_chunks(workspace_id);

-- ---------------------------------------------------------------------------
-- L1
-- ---------------------------------------------------------------------------
create table if not exists public.l1_artifacts (
  id uuid primary key default gen_random_uuid(),
  l0_id uuid references public.l0_artifacts(id) on delete set null,
  workspace_id uuid not null references public.workspaces(id) on delete restrict,
  kind text not null,
  schema_version int not null default 1,
  extractor text not null,
  model text,
  prompt_hash text,
  frontmatter jsonb not null default '{}'::jsonb,
  body text not null,
  embedding vector(1536),
  tags text[] not null default '{}',
  sensitivity sensitivity not null default 'internal',
  pii_tags text[] not null default '{}',
  supersedes_id uuid,
  quality_score text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);
create index if not exists l1_artifacts_workspace_idx on public.l1_artifacts(workspace_id);
create index if not exists l1_artifacts_l0_idx on public.l1_artifacts(l0_id);
create index if not exists l1_artifacts_kind_idx on public.l1_artifacts(workspace_id, kind);
create index if not exists l1_artifacts_created_at_idx on public.l1_artifacts(workspace_id, created_at);
create index if not exists l1_artifacts_supersedes_idx on public.l1_artifacts(supersedes_id);

-- Vector indexes (hnsw, cosine). Built unfilled here; bulk reindex in CI.
create index if not exists l0_chunks_embedding_hnsw_idx
  on public.l0_chunks using hnsw (embedding vector_cosine_ops);
create index if not exists l1_artifacts_embedding_hnsw_idx
  on public.l1_artifacts using hnsw (embedding vector_cosine_ops);

-- ---------------------------------------------------------------------------
-- L2 ontology (core)
-- ---------------------------------------------------------------------------
create table if not exists public.object_types (
  id uuid primary key default gen_random_uuid(),
  scope scope_kind not null,
  scope_id uuid,
  key text not null,
  name text not null,
  description text,
  schema_version int not null default 1,
  definition jsonb not null default '{}'::jsonb,
  label_singular text,
  label_plural text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);
create index if not exists object_types_scope_idx on public.object_types(scope, scope_id);
create unique index if not exists object_types_scope_key_version_uq
  on public.object_types(scope, scope_id, key, schema_version);

create table if not exists public.link_types (
  id uuid primary key default gen_random_uuid(),
  scope scope_kind not null,
  scope_id uuid,
  key text not null,
  name text not null,
  description text,
  from_type uuid not null references public.object_types(id) on delete restrict,
  to_type uuid not null references public.object_types(id) on delete restrict,
  kind link_kind not null default '1:N',
  definition jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);
create index if not exists link_types_scope_idx on public.link_types(scope, scope_id);
create unique index if not exists link_types_scope_key_uq on public.link_types(scope, scope_id, key);

create table if not exists public.action_types (
  id uuid primary key default gen_random_uuid(),
  scope scope_kind not null,
  scope_id uuid,
  key text not null,
  name text not null,
  description text,
  target_type uuid references public.object_types(id) on delete restrict,
  definition jsonb not null default '{}'::jsonb,
  requires_approval boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);
create index if not exists action_types_scope_idx on public.action_types(scope, scope_id);
create unique index if not exists action_types_scope_key_uq on public.action_types(scope, scope_id, key);

create table if not exists public.property_types (
  id uuid primary key default gen_random_uuid(),
  owner_type uuid not null references public.object_types(id) on delete cascade,
  key text not null,
  name text,
  data_type text not null,
  is_timeseries boolean not null default false,
  is_geotime boolean not null default false,
  is_required boolean not null default false,
  validations jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists property_types_owner_idx on public.property_types(owner_type);
create unique index if not exists property_types_owner_key_uq on public.property_types(owner_type, key);

create table if not exists public.entities (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id) on delete restrict,
  object_type_id uuid not null references public.object_types(id) on delete restrict,
  external_id text,
  name text not null,
  attributes jsonb not null default '{}'::jsonb,
  embedding vector(1536),
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);
create index if not exists entities_workspace_idx on public.entities(workspace_id);
create index if not exists entities_workspace_type_idx on public.entities(workspace_id, object_type_id);
create index if not exists entities_workspace_external_idx on public.entities(workspace_id, object_type_id, external_id);
create index if not exists entities_workspace_status_idx on public.entities(workspace_id, status);
create index if not exists entities_embedding_hnsw_idx
  on public.entities using hnsw (embedding vector_cosine_ops);

create table if not exists public.entity_links (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id) on delete restrict,
  link_type_id uuid not null references public.link_types(id) on delete restrict,
  from_entity uuid not null references public.entities(id) on delete cascade,
  to_entity uuid not null references public.entities(id) on delete cascade,
  attributes jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);
create index if not exists entity_links_workspace_idx on public.entity_links(workspace_id);
create index if not exists entity_links_from_idx on public.entity_links(workspace_id, from_entity);
create index if not exists entity_links_to_idx on public.entity_links(workspace_id, to_entity);
create index if not exists entity_links_type_idx on public.entity_links(workspace_id, link_type_id);

create table if not exists public.entity_actions (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id) on delete restrict,
  action_type_id uuid not null references public.action_types(id) on delete restrict,
  subject_entity uuid references public.entities(id) on delete set null,
  target_entity uuid references public.entities(id) on delete set null,
  actor_user_id uuid references public.users(id) on delete set null,
  actor_agent text,
  params jsonb not null default '{}'::jsonb,
  outcome text,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);
create index if not exists entity_actions_workspace_idx on public.entity_actions(workspace_id);
create index if not exists entity_actions_type_idx on public.entity_actions(workspace_id, action_type_id);
create index if not exists entity_actions_occurred_at_idx on public.entity_actions(workspace_id, occurred_at);
create index if not exists entity_actions_subject_idx on public.entity_actions(workspace_id, subject_entity);

-- ---------------------------------------------------------------------------
-- Audit log (partitioned by month)
-- ---------------------------------------------------------------------------
create table if not exists public.audit_log (
  id uuid not null default gen_random_uuid(),
  workspace_id uuid not null,
  actor_kind actor_kind not null,
  actor_id text not null,
  action text not null,
  resource text not null,
  resource_id uuid,
  before jsonb,
  after jsonb,
  diff jsonb,
  ip inet,
  ua text,
  request_id text,
  at timestamptz not null default now(),
  primary key (id, at)
) partition by range (at);

-- Seed the next 12 monthly partitions starting at the current month.
do $$
declare
  start_ts timestamptz := date_trunc('month', now());
  end_ts timestamptz;
  i int;
  part_name text;
begin
  for i in 0..11 loop
    end_ts := start_ts + interval '1 month';
    part_name := format('audit_log_%s', to_char(start_ts, 'YYYY_MM'));
    execute format(
      'create table if not exists public.%I partition of public.audit_log for values from (%L) to (%L);',
      part_name, start_ts, end_ts
    );
    execute format(
      'create index if not exists %I on public.%I (workspace_id, at);',
      part_name || '_workspace_idx', part_name
    );
    start_ts := end_ts;
  end loop;
end $$;

-- ---------------------------------------------------------------------------
-- updated_at touch trigger (reused by most tables)
-- ---------------------------------------------------------------------------
create or replace function public.touch_updated_at() returns trigger as $$
begin
  new.updated_at := now();
  return new;
end;
$$ language plpgsql;

do $$
declare
  t record;
begin
  for t in
    select table_name from information_schema.columns
    where table_schema = 'public'
      and column_name = 'updated_at'
      and table_name in (
        'platforms','agencies','workspaces','users','memberships',
        'l0_artifacts','l1_artifacts',
        'object_types','link_types','action_types','property_types',
        'entities','entity_links'
      )
  loop
    execute format('drop trigger if exists %I on public.%I', t.table_name || '_touch_updated', t.table_name);
    execute format(
      'create trigger %I before update on public.%I for each row execute function public.touch_updated_at();',
      t.table_name || '_touch_updated', t.table_name
    );
  end loop;
end $$;
